//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blood_Test_Unit.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Blood_Samples
    {
        [Required, Display(Name = "Sample ID")]
        public int sampleID { get; set; }
        public System.DateTime Date { get; set; }

        [Required, Display(Name = "Blood Sample")]
        public Nullable<int> Blood_Samples1 { get; set; }

        [Required, Display(Name = "DNA")]
        public Nullable<int> Dna { get; set; }

        [Required, Display(Name = "Turn Away")]
        public Nullable<int> Turn_Away { get; set; }
        public string Comment { get; set; }
    }
}
